# Generated by Django 4.2.19 on 2025-02-25 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Los Ángeles Lakers', max_length=150)),
                ('fundación', models.IntegerField()),
                ('ciudad', models.CharField(default='Los Ángeles, California', max_length=150)),
                ('campeonatos', models.IntegerField(default=15)),
                ('estadio', models.CharField(default='Crypto.com Arena', max_length=200)),
                ('logo_lakers', models.ImageField(blank=True, null=True, upload_to='equipos/')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('posición', models.CharField(default='', max_length=100)),
                ('número_remera', models.IntegerField()),
                ('foto_jugador', models.ImageField(blank=True, null=True, upload_to='jugador/')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugador', to='lakers.equipo')),
            ],
        ),
    ]
