# Generated by Django 4.2.19 on 2025-03-11 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lakers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jugador',
            old_name='número_remera',
            new_name='numero_remera',
        ),
    ]
