# Generated by Django 4.2.19 on 2025-03-11 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lakers', '0002_rename_número_remera_jugador_numero_remera'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='fundación',
            new_name='fundacion',
        ),
    ]
